class_info/0/color:
- 0.0
- 0.0
- 0.0
class_info/0/labels:
- -1
- 40
class_info/1/color:
- 140.0
- 109.0
- 49.0
class_info/1/labels:
- 0
class_info/10/color:
- 214.0
- 39.0
- 40.0
class_info/10/labels:
- 9
class_info/11/color:
- 44.0
- 160.0
- 44.0
class_info/11/labels:
- 10
class_info/12/color:
- 197.0
- 176.0
- 213.0
class_info/12/labels:
- 11
class_info/13/color:
- 227.0
- 119.0
- 194.0
class_info/13/labels:
- 12
class_info/14/color:
- 247.0
- 182.0
- 210.0
class_info/14/labels:
- 13
class_info/15/color:
- 165.0
- 81.0
- 148.0
class_info/15/labels:
- 14
class_info/16/color:
- 107.0
- 110.0
- 207.0
class_info/16/labels:
- 15
class_info/17/color:
- 173.0
- 73.0
- 74.0
class_info/17/labels:
- 16
class_info/18/color:
- 222.0
- 158.0
- 214.0
class_info/18/labels:
- 17
class_info/19/color:
- 214.0
- 97.0
- 107.0
class_info/19/labels:
- 18
class_info/2/color:
- 196.0
- 156.0
- 148.0
class_info/2/labels:
- 1
class_info/20/color:
- 188.0
- 189.0
- 34.0
class_info/20/labels:
- 19
class_info/21/color:
- 255.0
- 152.0
- 150.0
class_info/21/labels:
- 20
class_info/22/color:
- 132.0
- 60.0
- 57.0
class_info/22/labels:
- 21
class_info/23/color:
- 255.0
- 127.0
- 14.0
class_info/23/labels:
- 22
class_info/24/color:
- 206.0
- 109.0
- 189.0
class_info/24/labels:
- 23
class_info/25/color:
- 148.0
- 103.0
- 189.0
class_info/25/labels:
- 24
class_info/26/color:
- 255.0
- 187.0
- 120.0
class_info/26/labels:
- 25
class_info/27/color:
- 123.0
- 65.0
- 115.0
class_info/27/labels:
- 26
class_info/28/color:
- 152.0
- 223.0
- 138.0
class_info/28/labels:
- 27
class_info/29/color:
- 206.0
- 219.0
- 156.0
class_info/29/labels:
- 28
class_info/3/color:
- 158.0
- 218.0
- 229.0
class_info/3/labels:
- 2
class_info/30/color:
- 219.0
- 219.0
- 141.0
class_info/30/labels:
- 29
class_info/31/color:
- 82.0
- 84.0
- 163.0
class_info/31/labels:
- 30
class_info/32/color:
- 189.0
- 158.0
- 57.0
class_info/32/labels:
- 31
class_info/33/color:
- 23.0
- 190.0
- 207.0
class_info/33/labels:
- 32
class_info/34/color:
- 99.0
- 121.0
- 57.0
class_info/34/labels:
- 33
class_info/35/color:
- 231.0
- 186.0
- 82.0
class_info/35/labels:
- 34
class_info/36/color:
- 231.0
- 203.0
- 148.0
class_info/36/labels:
- 35
class_info/37/color:
- 199.0
- 199.0
- 199.0
class_info/37/labels:
- 36
class_info/38/color:
- 174.0
- 199.0
- 232.0
class_info/38/labels:
- 37
class_info/39/color:
- 140.0
- 162.0
- 82.0
class_info/39/labels:
- 38
class_info/4/color:
- 231.0
- 150.0
- 156.0
class_info/4/labels:
- 3
class_info/40/color:
- 156.0
- 158.0
- 222.0
class_info/40/labels:
- 39
class_info/5/color:
- 127.0
- 127.0
- 127.0
class_info/5/labels:
- 4
class_info/6/color:
- 181.0
- 207.0
- 107.0
class_info/6/labels:
- 5
class_info/7/color:
- 140.0
- 86.0
- 75.0
class_info/7/labels:
- 6
class_info/8/color:
- 31.0
- 119.0
- 180.0
class_info/8/labels:
- 7
class_info/9/color:
- 57.0
- 59.0
- 121.0
class_info/9/labels:
- 8
classes:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
default_color:
- 0.0
- 0.0
- 0.0
